# docker-Specify the compose version
version: "3"

services:
  app:
    build: 
      context: .
      dockerfile: app/Dockerfile
    tty: true
    depends_on:
      - chromadb
      - unstructured
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - TORCH_HOME=/data/models
      - HF_HOME=/data/models
    volumes: 
      - ./app/main.py:/app/main.py
      - ./app/entrypoint.sh:/app/entrypoint.sh
      - ./app/lib:/app/lib
      - ./data/models:/data/models
      # - ./app/test:/app/test
      # - ./data/uploads:/data/uploads
      
      # - ./data/output_segments:/data/output_segments

  chromadb:
    image: chromadb/chroma
    volumes:
      - chromadb_data:/chroma/data
    environment:
      - CHROMA_TELEMETRY_ENABLED=False

  unstructured:
    build: 
      context: unstructured
    ports:
      - "8080:8080"
    env_file:
      - .env
    volumes:
      - ./data/unstructured:/data
      # - ./data/unstructured-uploads:/uploads
      - ./unstructured/app.py:/app/app.py
      - ./unstructured/lib:/app/lib
      - ./unstructured/entrypoint.sh:/app/entrypoint.sh

  nginx:
    image: nginx:1.27.4-alpine3.21-perl
    depends_on:
      - app
    ports:
      - "8888:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    env_file:
      - .env
    restart: on-failure

  index:
    build: 
      context: index
    ports:
      - "8889:8889"
    depends_on:
      - app

volumes:
  chromadb_data: