# docker-Specify the compose version
version: "3"

services:
  app:
    build: 
      context: .
      dockerfile: app/Dockerfile
    tty: true
    depends_on:
      - chromadb
      - unstructured
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - TORCH_HOME=/data/models
      - HF_HOME=/data/models
    volumes: 
      - ./app/main.py:/app/main.py
      - ./app/lib:/app/lib
      - ./app/test:/app/test
      - ./data/uploads:/data/uploads

  chromadb:
    image: chromadb/chroma
    volumes:
      - chromadb_data:/chroma/data

  unstructured:
    build: 
      context: unstructured
    ports:
      - "8080:8080"
    volumes:
      - ./data/unstructured:/data
      - ./data/unstructured-uploads:/uploads
      - ./unstructured/app.py:/app/app.py
      - ./unstructured/lib:/app/lib

volumes:
  chromadb_data: