# docker-Specify the compose version
version: "3"

services:
  app:
    build: 
      context: .
      dockerfile: app/Dockerfile
    # image: pudding/github-action-app:puppeteer-python-14-action-rss-20230826-1641
    tty: true
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - TORCH_HOME=/data/models
      - HF_HOME=/data/models
    volumes: 
      - ./app/main.py:/app/main.py
      - ./app/lib:/app/lib
      - ./app/images:/app/images
      # - ./package.json:/app/package.json
      # - ./data/models:/data/models
      - ./data/uploads:/data/uploads

  chromadb:
    image: chromadb/chroma
    volumes:
      - chromadb_data:/chroma/data

  # unstructured:
  #   build: 
  #     context: unstructured
  #   ports:
  #     - "8080:8080"
  #   volumes:
  #     - ./data/unstructured:/data  # 儲存處理過的文件
  #     - ./data/unstructured-uploads:/uploads  # 儲存處理過的文件
  #     - ./unstructured/app.py:/app/app.py
  #     - ./unstructured/lib:/app/lib

  # mongodb:
  #   image: mongo:8.0.5
  #   environment:d
  #     - MONGO_INITDB_ROOT_USERNAME=admin
  #     - MONGO_INITDB_ROOT_PASSWORD=secret  # 修改為安全密碼
  #   volumes:
  #     - ./cache/mongo:/data/db

volumes:
  chromadb_data: