FROM python:3.10

WORKDIR /app

# 安裝中文字型 & 其他依賴
RUN apt-get update && apt-get install -y \
    fonts-noto-cjk \
    poppler-utils \
    tesseract-ocr \
    tesseract-ocr-chi-sim \
    tesseract-ocr-chi-tra \
    && rm -rf /var/lib/apt/lists/*

# 設置環境變數，讓 Unstructured API 支援中文字體
ENV UNSTRUCTURED_HF_CACHE_DIR=/app/cache

COPY requirements.txt requirements.txt
RUN pip install --no-cache-dir -r requirements.txt
RUN pip install pillow_heif
RUN pip install "unstructured[all-docs]"

CMD ["python", "/app/app.py"]

COPY app.py /app/app.py
